### ISSUE TITLE
UndefVarError when trying to use at-cse

### ISSUE THREAD

**Issue by dpsanders** [rdeits/CommonSubexpressions.jl#2]
```
julia> @cse (x + y)^2 + (x+y)
UndefVarError: x not defined
```

**Comment by rdeits** [comment]
Silly question, but are x and y in fact defined in your scope? `@cse`replaces your expression in-place, so that replaced expression automatically gets evaluated.

**Comment by dpsanders** [comment]
Ah, for some reason I expected it to return the expression itself. That would be a useful feature. Is there some function / macro that does that?

**Comment by rdeits** [comment]
I think `macroexpand` is the answer for that, although it's a bit awkward to use: 

```julia
julia> macroexpand(:(@cse (x + y)^2 + (x+y)))
quote
    ##+#270 = x + y
    ##^#271 = ##+#270 ^ 2
    ##+#272 = ##^#271 + ##+#270
    ##+#272
end
```

**Comment by rdeits** [comment]
Or if you already have the expression, you can just use the internal `combine_subexprs!` function: 

```julia
julia> expr = :((x + y)^2 + (x+y))
:((x + y) ^ 2 + (x + y))

julia> CommonSubexpressions.combine_subexprs!(expr)
quote
    ##+#273 = x + y
    ##^#274 = ##+#273 ^ 2
    ##+#275 = ##^#274 + ##+#273
    ##+#275
end

```

**Comment by rdeits** [comment]
#5 exports the `cse()` function that takes an expression and returns the modified expression, which should be the right tool for this.

**Comment by dpsanders** [comment]
Thanks!
