### ISSUE TITLE
Publish the package?

### ISSUE THREAD

**Issue by dpsanders** [rdeits/CommonSubexpressions.jl#3]
I am using this package in the `dag` branch of `TreeView.jl` to draw DAGs:

https://github.com/dpsanders/TreeView.jl/blob/af011c8a9785f0d762d0954844767a19e038e37a/examples/DAG.ipynb

So it would be great if you could publish it!

**Comment by rdeits** [comment]
on it: https://github.com/JuliaLang/METADATA.jl/pull/7753

**Comment by dpsanders** [comment]
👍

**Comment by rdeits** [comment]
ok, done
