### ISSUE TITLE
Use less messy symbols

### ISSUE THREAD

**Issue by dpsanders** [rdeits/CommonSubexpressions.jl#4]
You could use something less messy instead of those `gensym`s.
For example,  the first 15 lines of 

https://github.com/dpsanders/IntervalConstraintProgramming.jl/blob/1eeb1133e6c2474844599d2290d0696a35779250/src/ast.jl

give you a function  `make_symbol()` that will return something like `_z_2_`.
(Mike Innes uses random animal names.)

**Comment by rdeits** [comment]
I cleaned up the symbols in 3aba2566307608402a5db8f2f5bc8071ada2e1b9 . They're still gensyms, but now they're short and unique instead of incredibly long. I do like the animal name solution, though...

**Comment by dpsanders** [comment]
Thanks.
